# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06orders\"O\n\tOrderItem\x12\x0f\n\x07product\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x10\n\x08subtotal\x18\x04 \x01(\x01\"\x82\x01\n\rOrderResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x63ustomer\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05total\x18\x04 \x01(\x01\x12\x12\n\nitem_count\x18\x05 \x01(\x05\x12 \n\x05items\x18\x06 \x03(\x0b\x32\x11.orders.OrderItem\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"#\n\x11ListOrdersRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\";\n\x12ListOrdersResponse\x12%\n\x06orders\x18\x01 \x03(\x0b\x32\x15.orders.OrderResponse\"H\n\x12\x43reateOrderRequest\x12\x10\n\x08\x63ustomer\x18\x01 \x01(\t\x12 \n\x05items\x18\x02 \x03(\x0b\x32\x11.orders.OrderItem2\xd1\x01\n\x0cOrderService\x12:\n\x08GetOrder\x12\x17.orders.GetOrderRequest\x1a\x15.orders.OrderResponse\x12\x43\n\nListOrders\x12\x19.orders.ListOrdersRequest\x1a\x1a.orders.ListOrdersResponse\x12@\n\x0b\x43reateOrder\x12\x1a.orders.CreateOrderRequest\x1a\x15.orders.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERITEM']._serialized_start=24
  _globals['_ORDERITEM']._serialized_end=103
  _globals['_ORDERRESPONSE']._serialized_start=106
  _globals['_ORDERRESPONSE']._serialized_end=236
  _globals['_GETORDERREQUEST']._serialized_start=238
  _globals['_GETORDERREQUEST']._serialized_end=273
  _globals['_LISTORDERSREQUEST']._serialized_start=275
  _globals['_LISTORDERSREQUEST']._serialized_end=310
  _globals['_LISTORDERSRESPONSE']._serialized_start=312
  _globals['_LISTORDERSRESPONSE']._serialized_end=371
  _globals['_CREATEORDERREQUEST']._serialized_start=373
  _globals['_CREATEORDERREQUEST']._serialized_end=445
  _globals['_ORDERSERVICE']._serialized_start=448
  _globals['_ORDERSERVICE']._serialized_end=657
# @@protoc_insertion_point(module_scope)
