from typing import Protocol

from .entities import Order
from .events import DomainEvent


class OrderRepository(Protocol):
    def save(self, order: Order) -> Order: ...
    def find_by_id(self, order_id: int) -> Order | None: ...
    def find_all(self) -> list[Order]: ...
    def find_by_status(self, status: str) -> list[Order]: ...
    def delete(self, order_id: int) -> bool: ...


class UnitOfWork(Protocol):
    orders: OrderRepository

    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class EventPublisher(Protocol):
    def publish(self, events: list[DomainEvent]) -> None: ...
